parameters:
#    stonino_main.example.class: Stonino\MainBundle\Example

services:
#    stonino_main.example:
#        class: %stonino_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
